<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="dados">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="escolas" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="escola" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="nome" type="xs:string"/>
                    <xs:element name="localidade" type="xs:string"/>
                    <xs:element name="area" type="xs:string"/>
                    <xs:element name="contacto">
                      <xs:simpleType>
                        <xs:restriction base="xs:string">
                          <xs:pattern value="[29][0-9]{8}"/>
                        </xs:restriction>
                      </xs:simpleType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="tipo" use="required">
              <xs:simpleType>
                <xs:restriction base="xs:string">
                  <xs:enumeration value="profissional"/>
                  <xs:enumeration value="academico"/>
                </xs:restriction>
              </xs:simpleType>
            </xs:attribute>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>